version: '3.4'
services:
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${CONFIG_ROOT}/sabnzbd:/config # config files
      - ${NFS_ROOT}/downloads:/downloads
      - ${NFS_ROOT}/incomplete-downloads:/incomplete-downloads #optional

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${CONFIG_ROOT}/sonarr:/config # config files
      - ${NFS_ROOT}/media/tv:/tv # tv shows folder
      - ${NFS_ROOT}/downloads:/downloads # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${CONFIG_ROOT}/radarr:/config # config files
      - ${NFS_ROOT}/media/movies:/movies # movies folder
      - ${NFS_ROOT}/downloads:/downloads # download folder

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1002
      - PGID=1003
      - VERSION=docker
      - UMASK_SET=022
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${CONFIG_ROOT}/plex/db:/config # plex database
      - ${CONFIG_ROOT}/plex/transcode:/transcode # temp transcoded files
      - ${NFS_ROOT}/media:/media
    restart: unless-stopped
