version: '3.4'
services:
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/sabnzbd:/config
      - ${NFS_ROOT}/downloads:/downloads
      - ${NFS_ROOT}/incomplete-downloads:/incomplete-downloads

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/sonarr:/config
      - ${NFS_ROOT}/media/tv:/tv
      - ${NFS_ROOT}/downloads:/downloads

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/radarr:/config
      - ${NFS_ROOT}/media/movies:/movies
      - ${NFS_ROOT}/downloads:/downloads

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1002
      - PGID=1003
      - VERSION=docker
      - UMASK_SET=022
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${CONFIG_ROOT}/plex/db:/config
      - ${CONFIG_ROOT}/plex/transcode:/transcode
      - ${NFS_ROOT}/media:/media
    restart: unless-stopped
